//#############################################################################
//  File:      VRConnectFourConstants.h
//  Author:    Cedric Renggli, Marc Wacker, Roman Kühne
//  Date:      Mai 2014
//#############################################################################

#ifndef VRCONNECTFOURCONSTANTS_H
#define VRCONNECTFOURCONSTANTS_H

#include "VRBoardGameConstants.h"

#define CONNECTFOUR_GROUD_WIDHT_DEPTH					1.0f
#define CONNECTFOUR_GROUD_HEIGHT						0.1f

#define CONNECTFOUR_CYLINDERS_RADIUS					0.025f
#define CONNECTFOUR_CYLINDERS_DISTANCE					0.25f
#define CONNECTFOUR_SPHERES_RADIUS						0.05f
#define CONNECTFOUR_Y_SPHERE_OFFSET						2.1f * (CONNECTFOUR_SPHERES_RADIUS - sqrtf((CONNECTFOUR_SPHERES_RADIUS * CONNECTFOUR_SPHERES_RADIUS) - (CONNECTFOUR_CYLINDERS_RADIUS * CONNECTFOUR_CYLINDERS_RADIUS)))

#define CONNECTFOUR_CYLINDERS_HEIGH						(8.0f * CONNECTFOUR_SPHERES_RADIUS) - (3.5f * CONNECTFOUR_Y_SPHERE_OFFSET)

#define CONNECTFOUR_BOARD_Y_OFFSET						0.5f

#define CONNECTFOUR_NUMBER_OF_ROWS_COLUMNS_LEVELS		4
#define CONNECTFOUR_NUMBER_OF_CYLINDERS					(CONNECTFOUR_NUMBER_OF_ROWS_COLUMNS_LEVELS * CONNECTFOUR_NUMBER_OF_ROWS_COLUMNS_LEVELS)

#define CONNECTFOUR_PLAYER0_COLOR_NAME					"Green"
#define CONNECTFOUR_PLAYER1_COLOR_NAME					"Red"
#define CONNECTFOUR_PLAYER0_COLOR_VALUE					SLCol4f::GREEN
#define CONNECTFOUR_PLAYER1_COLOR_VALUE					SLCol4f::RED

#endif